# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    AccountBundle\Entity\User : plaintext
    

  providers:
        user_db:
            entity: { class: AccountBundle\Entity\User, property: username}
            
  role_hierarchy:

        # Un admin hérite des droits d'auteur et de modérateur

        ROLE_ADMIN:       [ROLE_USER]

  firewalls:
      
    main:
      pattern:      ^/
      anonymous:    true
      security: true
      form_login:
        default_target_path: /Marquis
        login_path: /connexion
        check_path: /login_check
      logout:
        path:       /logout
        target:     /Marquis

  access_control:

      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: ROLE_USER }
      