# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    AccountBundle\Entity\User : plaintext
    




 
  providers:
        user_db:
            entity: { class: AccountBundle\Entity\User, property: username}
        
        
  firewalls:
      
    main:
      pattern:      ^/
      anonymous:    true
      security: true
      form_login:
        default_target_path: /Marquis
        login_path: /connexion
        check_path: /login_check
      logout:
        path:       /logout
        target:     /Marquis

  access_control:

      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: ROLE_USER }
      #- { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }