<?php

namespace AccountBundle\Repository;

/**
 * connexionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class connexionRepository extends \Doctrine\ORM\EntityRepository
{
}
