<?php

namespace AccountBundle\Repository;

/**
 * PointsVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointsVenteRepository extends \Doctrine\ORM\EntityRepository
{
}
